### ISSUE TITLE
Tox missing setup.py error

### ISSUE THREAD

**Issue by djoreilly** [SUSE/BCI-tests#127]
Since https://github.com/SUSE/BCI-tests/commit/3a04ab7b259a2f21d7986617e5726f499f5f5722#diff-ef2cef9f88b4fe09ca3082140e67f5ad34fb65fb6e228f119d3812261ae51449L5 removed `skipsdist = True` from tox.ini, getting this:

```
# tox -e init 
Traceback (most recent call last):
  File "/usr/bin/tox", line 11, in <module>
    load_entry_point('tox==2.9.1', 'console_scripts', 'tox')()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 40, in main
    retcode = Session(config).runcommand()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 392, in runcommand
    return self.subcommand_test()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 552, in subcommand_test
    path = self.get_installpkg_path()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 528, in get_installpkg_path
    path = self._makesdist()
  File "/usr/lib/python3.6/site-packages/tox/session.py", line 407, in _makesdist
    raise tox.exception.MissingFile(setup)
tox.MissingFile: MissingFile: /root/BCI-tests/setup.py
```

**Comment by grisu48** [comment]
Hmm, weird I cannot reproduce this issue. Here `tox -e init` works just fine. Can you try again?

**Comment by dcermak** [comment]
This is most likely due to a very old version of pip or tox. @djoreilly Is this still an issue?

**Comment by djoreilly** [comment]
> This is most likely due to a very old version of pip or tox. @djoreilly Is this still an issue?

Don't have the env anymore to test. The tox version was 2.9.1 (in the stacktrace) which is quite old. Seems I was using the tox from Leap 15.4 python-tox, instead of from pip. Should close this issue.
