### ISSUE TITLE
First failures in PostgreSQL tests

### ISSUE THREAD

**Issue by jlausuch** [SUSE/BCI-tests#231]
1) `RuntimeError: Container xyz did not become healthy within 45000.0ms`
After looking at all the tests, I have observed that it needs between 45s and 50s on x86_64, but for safety I would go to 60s timeout.
e.g. https://openqa.suse.de/tests/10880049

2) `SyntaxError: invalid syntax`
In other architectures != x86_64 the tox command fails with:
```
wa/psycopg2_ee724a19d7ac48d894cf733efbd3685e/
  Complete output (6 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fwlvwwwa/psycopg2_ee724a19d7ac48d894cf733efbd3685e/setup.py", line 225
      except Warning, w:
                    ^
  SyntaxError: invalid syntax
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/2d/d7/496da11d7c81971870ddd36800419c4f84e8f6208aac5eabedf9f7748729/psycopg2-2.0.11.tar.gz#sha256=e6b4e0e41df97441eff34e00065376414da6488e0d55848a45cd77551dbae434 (from https://pypi.org/simple/psycopg2/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached psycopg2-2.0.10.tar.gz (255 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /root/BCI-tests/.tox/postgres/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fwlvwwwa/psycopg2_f8a4bace0e584dc1a9ae18dfe83aa00f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fwlvwwwa/psycopg2_f8a4bace0e584dc1a9ae18dfe83aa00f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mh15ro96
       cwd: /tmp/pip-install-fwlvwwwa/psycopg2_f8a4bace0e584dc1a9ae18dfe83aa00f/
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-fwlvwwwa/psycopg2_f8a4bace0e584dc1a9ae18dfe83aa00f/setup.py", line 50, in <module>
      import ConfigParser
  ModuleNotFoundError: No module named 'ConfigParser'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/19/79/35c7596bab4456f3610c12ec542a94d51c6781ced587d1d85127210b879b/psycopg2-2.0.10.tar.gz#sha256=e40cc04b43849085725076ae134bfef9e3b087f6dd7c964aeeb930e2f0bc14ab (from https://pypi.org/simple/psycopg2/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement psycopg2 (from versions: 2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.0.14, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6, 2.6.1, 2.6.2, 2.7, 2.7.1, 2.7.2, 2.7.3, 2.7.3.1, 2.7.3.2, 2.7.4, 2.7.5, 2.7.6, 2.7.6.1, 2.7.7, 2.8, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 2.9.6)
ERROR: No matching distribution found for psycopg2

=================================== log end ====================================
ERROR: could not install deps [pytest, pytest-testinfra, pytest-xdist ; python_version >= "3.6", dataclasses ; python_version < "3.7", pytest-rerunfailures, typing_extensions, git+https://github.com/dcermak/pytest_container, psycopg2]; v = InvocationError('/root/BCI-tests/.tox/postgres/bin/python -m pip install pytest pytest-testinfra \'pytest-xdist ; python_version >= "3.6"\' \'dataclasses ; python_version < "3.7"\' pytest-rerunfailures typing_extensions git+https://github.com/dcermak/pytest_container psycopg2', 1)
___________________________________ summary ____________________________________
ERROR:   postgres: could not install deps [pytest, pytest-testinfra, pytest-xdist ; python_version >= "3.6", dataclasses ; python_version < "3.7", pytest-rerunfailures, typing_extensions, git+https://github.com/dcermak/pytest_container, psycopg2]; v = InvocationError('/root/BCI-tests/.tox/postgres/bin/python -m pip install pytest pytest-testinfra \'pytest-xdist ; python_version >= "3.6"\' \'dataclasses ; python_version < "3.7"\' pytest-rerunfailures typing_extensions git+https://github.com/dcermak/pytest_container psycopg2', 1)
```
reference: https://openqa.suse.de/tests/10879980#step/bci_test_podman/45

**Comment by dirkmueller** [comment]
@jlausuch please create one issue for each issue. 

Regarding: psycopg2: please install python3-psycopg2 outside, afaik it is available in SLES for all architectures.

Regarding health: that's an incredibly long timeout. It takes about 5s on my 7 year old workstation. There's something wrong.

**Comment by jlausuch** [comment]
> @jlausuch are you still seeing these errors?

no, sorry, tests are good now, thanks!
